20221223 12:58:24 INFO     engine : served at port: "8000".
20221223 12:58:24 INFO     engine : platform: "Linux-5.10.63-v7l+-armv7l-with-debian-10.11".
20221223 12:58:24 INFO     engine : machine: "armv7l".
20221223 12:58:24 INFO     engine : python version: "3.7.3".
20221223 12:58:24 INFO     engine : django version: "(3, 2, 16, 'final', 0)".
20221223 12:58:24 INFO     engine : bots version: "3.3.0".
20221223 12:58:24 INFO     engine : bots installation path: "/home/pi/Documents/raspimapper/bots/utils".
20221223 12:58:24 INFO     engine : config path: "/home/pi/Documents/raspimapper/raspimapper".
20221223 12:58:24 INFO     engine : botssys path: "/home/pi/Documents/raspimapper/bots/utils/botssys".
20221223 12:58:24 INFO     engine : usersys path: "/home/pi/Documents/raspimapper/bots/usersys".
20221223 12:58:24 INFO     engine : local date/time: "2022-12-23T12:58:24.025627".
20221223 12:58:24 INFO     engine : DATABASE_ENGINE: "django.db.backends.sqlite3".
20221223 12:58:24 INFO     engine : DATABASE_NAME: "/home/pi/Documents/raspimapper/db.sqlite3".
20221223 12:58:24 INFO     engine : DATABASE_USER: "".
20221223 12:58:24 INFO     engine : DATABASE_HOST: "".
20221223 12:58:24 INFO     engine : DATABASE_PORT: "".
20221223 12:58:24 INFO     engine : DATABASE_OPTIONS: "{}".
20221223 12:58:24 INFO     engine : Connected to database.
20221223 12:58:24 DEBUG    engine : No import of module "/home/pi/Documents/raspimapper/bots/usersys/routescripts/botsengine": No module named 'bots.usersys.routescripts.botsengine'.
20221223 12:58:24 INFO     engine : This run is an acceptance test - as indicated in option "runacceptancetest" in bots.ini.
20221223 12:58:24 DEBUG    engine : Imported "/home/pi/Documents/raspimapper/bots/usersys/routescripts/bots_acceptancetest".
20221223 12:58:24 CRITICAL engine : !Bots database is locked!
Bots-engine has ended in an unexpected way during the last run.
Most likely causes: sudden power-down, system crash, problems with disk I/O, bots-engine terminated by user, etc.
Bots will do an automatic crash recovery now.
20221223 12:58:24 DEBUG    engine : Run userscript "pretest" in "/home/pi/Documents/raspimapper/bots/usersys/routescripts/bots_acceptancetest".
20221223 12:58:24 INFO     engine : Run "crashrecovery".
20221223 12:58:24 INFO     engine : Run all active routes from database: "['myfirstroute']".
20221223 12:58:24 DEBUG    engine : No import of module "/home/pi/Documents/raspimapper/bots/usersys/routescripts/myfirstroute": No module named 'bots.usersys.routescripts.myfirstroute'.
20221223 12:58:24 INFO     engine : Running route myfirstroute 9999
20221223 12:58:24 DEBUG    engine : Start communication channel "myfirstroute_in" type file in.
20221223 12:58:24 DEBUG    engine : Channel "myfirstroute_in" adapted for acceptance test: type "file", testpath "".
20221223 12:58:24 DEBUG    engine : No import of module "/home/pi/Documents/raspimapper/bots/usersys/communicationscripts/myfirstroute_in": No module named 'bots.usersys.communicationscripts.myfirstroute_in'.
20221223 12:58:24 DEBUG    engine : Finished communication channel "myfirstroute_in" type file in.
